export const productsArray = [
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product3.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Скор 250 ЕС к.э.",
    productimgurl: "/static/image/product1.png",
    sku: "A22480",
    customerprice: 11.5,
  },
  {
    productid: 26,
    category: "Facility",
    productname: "Петунія Софістика F1",
    productimgurl: "/static/image/product2.png",
    sku: "A22480",
    customerprice: 11.5,
  },
];
